# Generated by Django 6.0.3 on 2026-03-15 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_image', models.ImageField(upload_to='bike_images/')),
                ('bike_number', models.CharField(max_length=20)),
                ('bike_model', models.CharField(max_length=25)),
                ('bike_owner', models.CharField(max_length=100)),
                ('owner_image', models.ImageField(upload_to='owner_images/')),
                ('owner_mobile', models.CharField(max_length=10)),
                ('owner_address', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('amount_per_hour', models.DecimalField(decimal_places=2, max_digits=6)),
                ('available_from', models.TimeField()),
                ('available_to', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
