# Generated by Django 6.0.3 on 2026-03-15 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='bike_image',
            field=models.ImageField(default='default.jpg', upload_to='bike_images/'),
        ),
    ]
